# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.0
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-02-22T03:28:13Z"
  labels:
    app: ja-personal-website-container-pod
  name: ja-personal-website-container-pod-deployment
spec:
  selector:
    matchLabels:
      app: ja-personal-website-container-pod
  template:
    metadata:
      creationTimestamp: "2024-02-22T03:28:13Z"
      labels:
        app: ja-personal-website-container-pod
      name: ja-personal-website-container-pod
    spec:
      containers:
      - image: localhost/ja-personal-website:latest
        name: ja-personal-website-container
        ports:
        - containerPort: 8080
          hostPort: 8000
