# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.0
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-02-21T04:12:59Z"
  labels:
    app: ja-personal-website-container-pod
  name: ja-personal-website-container-pod-deployment
spec:
  selector:
    matchLabels:
      app: ja-personal-website-container-pod
  template:
    metadata:
      creationTimestamp: "2024-02-21T04:12:59Z"
      labels:
        app: ja-personal-website-container-pod
      name: ja-personal-website-container-pod
    spec:
      containers:
      - env:
        - name: ASPNETCORE_URLS
          value: http://*:80
        image: localhost/ja-personal-website:latest
        name: ja-personal-website-container
        ports:
        - containerPort: 80
          hostPort: 9999
